### ISSUE TITLE
missing contributor guidelines

### ISSUE THREAD

**Issue by tomjemmett** [nhs-r-community/demos-and-how-tos#30]
this repo is missing contributor guidelines

**Comment by GirlThatGraphs** [comment]
https://github.com/larymak/Python-project-Scripts/blob/main/CONTRIBUTING.md

looks like a useful starting point

**Comment by harrietrs** [comment]
@tomjemmett does #33 resolve this issue?
Conscious you wrote "_guidelines_"- did you mean how-tos? Or were you talking about criteria contributions should meet? (e.g. [GDS-style](https://github.com/alphagov/govuk-frontend/blob/main/CONTRIBUTING.md)- probs a bit over-engineered for us?)

**Comment by tomjemmett** [comment]
I think #33 does a good job of the how to contribute, but we probably should have something like what you linked to. I think other repo's in NHS-R have used [contributor-covenant.org](https://www.contributor-covenant.org/) - not sure what others think?

**Comment by ChrisBeeley** [comment]
Really and truly we should have a generic one I suppose. Which repo does it best at the moment, anyone know?

**Comment by Lextuga007** [comment]
We do need contributing guidelines and looking at RStudio/Posit:

https://github.com/rstudio/rstudio/blob/main/CONTRIBUTING.md

They have a few parts to it but not as detailed as the example @harrietrs has shared (but thank you as that's a great link which some parts will be very useful too I think):

- [ ] Filing Bugs
- [ ] Enhancements
- [ ] Contributing Code
- [ ] Code of Conduct

And on Code of Conduct we need to have slightly different ones for events and communication channels like Slack and I really like the ones outlined by the Bristol Data Ethics Club:

https://dataethicsclub.com/contents/join_in/code-of-conduct.html 

They also have a contributing page too: https://dataethicsclub.com/contents/join_in/contributing.html 

We need to have this across all repositories in one form or another so I wonder if it's best to have a single repository (in assets for example) or a repo that can be built into it's own site - like Bristol Data Ethics Club have done - with links to the specific pages? That would make it accessible for those who are going to events and perhaps not that familiar yet with GitHub.

**Comment by Lextuga007** [comment]
Also worthy of note, either to help with this or to feedback to NHS Pycom who have https://nhs-pycom.net/code_of_conduct/ but I can't find the same as a CONTRIBUTING.md on their GitHub https://github.com/nhs-pycom. I'll prompt a conversation about this in their Slack.

**Comment by Lextuga007** [comment]
Not quite the same but I love this email notification on the Data Hazards repository for an out of office - https://github.com/very-good-science/data-hazards/blob/main/.github/workflows/out-of-office.yml. We should have something on our repositories to say thank you for the contributions 😃

**Comment by craig-shenton** [comment]
Ah, thanks for pointing that out Zoe. I did include a very generic section in the website readme (copied from jekyll), but the [CONTRIBUTING.md]() does not go anywhere!

> Contributions are what make the open source community such an amazing place to learn, inspire, and create. Any contributions you make are **greatly appreciated**.
> 
> 1. Fork the Project
> 2. Create your Feature Branch (`git checkout -b feature/AmazingFeature`)
> 3. Commit your Changes (`git commit -m 'Add some AmazingFeature'`)
> 4. Push to the Branch (`git push origin feature/AmazingFeature`)
> 5. Open a Pull Request
> 
> _See [CONTRIBUTING.md]() for detailed guidance._

I always though these files would be better managed at a organisaition level. But it would be good to standardise these between NHS orgs. Happy to take your lead on that. We are also thinking of using [pkgdown](https://pkgdown.r-lib.org/articles/pkgdown.html) to generate a docs site for each repo like you guys do, but will have to think how that will work with python.

**Comment by Lextuga007** [comment]
My fault I think I typed contribution rather than contributing when looking for it! Yes, there's definitely a need for technical contributions like [NHS Pycom](https://github.com/nhs-pycom/nhs.pycom#contributing) and [GDS style](https://github.com/alphagov/govuk-frontend/blob/main/CONTRIBUTING.md) but also a high level guide incorporating expected behaviour. It would be fantastic to standardise between ourselves too! 💯 

On the pkgdown with Python I'm not sure it's supported (there is a closed issue on the pkgdown GitHub) but could quarto be helpful?

**Comment by craig-shenton** [comment]
Yep, was thinking the same. I've been getting into Quarto myself recently ([https://craig-shenton.github.io/quarto-nhs-theme/](https://craig-shenton.github.io/quarto-nhs-theme/)), and my team at NHSE is also interested in standard reporting using Quarto. I will share anything we develop as it will be done in R.
