### ISSUE TITLE
Read in multiple Excel files / sheets with purrr

### ISSUE THREAD

**Issue by johnmackintosh** [nhs-r-community/demos-and-how-tos#6]
Examples of reading in multiple worksheets, or multiple workbooks, and combining into a dataframe / tibble for further processing /analysis

**Comment by tomjemmett** [comment]
I’ve possibly got a gist that could be repurposed for this somewhere… Not sure if you were planning on writing something @johnmackintosh, or want to collab, or just suggesting? Happy either way 🙂

**Comment by johnmackintosh** [comment]
Was a hopeful suggestion @tomjemmet :) I know someone had a version knocking about on twitter a while back, and Fiona Grimm had a cool example that I can never find in my bookmarks, but the more the merrier, so, absolutely want to see whatever you have Tom

**Comment by ChrisBeeley** [comment]
I did this here https://github.com/ChrisBeeley/literacy_assessments

Just needs a bit of a tidy up to make it more generic and clearer

**Comment by ChrisBeeley** [comment]
Closed by #9 - thanks @johnmackintosh !
